import type { Story } from "../types/Story";

export const week_stories: Story[] = [
  {
    id: 206,
    count: 58,
    type: "week",
    title: "من 5 لـ 11 فبراير",
    year: "2026",
    summary:
      "حصدت كل الزرع - تحديث جديد للموقع - دراسة - شغل - بخلص موضوع الجامعة",
    special: false,
    seen: true,
  },
  {
    id: 204,
    count: 57,
    type: "week",
    title: "من 29 يناير لـ 4 فبراير",
    year: "2026",
    summary: "حصاد الزرع - خلصت شغل المونتاج - دراسة",
    special: false,
    seen: true,
  },
  {
    id: 199,
    count: 56,
    type: "week",
    title: "من 22 لـ 28 يناير",
    year: "2026",
    summary: "شغل المونتاج، بتعلم أشياء جديدة",
    special: false,
    seen: true,
  },
  {
    id: 194,
    count: 55,
    type: "week",
    title: "من 15 لـ 21 يناير",
    year: "2026",
    summary: "مشاريع جديدة",
    special: false,
    seen: true,
  },
  {
    id: 190,
    count: 54,
    type: "week",
    title: "من 8 لـ 14 يناير",
    year: "2026",
    summary: "مشروع المتجر",
    special: false,
    seen: true,
  },
  {
    id: 154,
    count: 53,
    type: "week",
    title: "من 1 لـ 7 يناير",
    year: "2026",
    summary: "اضافات جديدة للموقع - زر الاعدادات",
    special: false,
    seen: true,
  },
];
